# Generated by Django 5.1.3 on 2024-11-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0002_add_comunas_linares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='telefono',
            field=models.CharField(max_length=9),
        ),
    ]
