# Generated by Django 5.1.3 on 2024-11-14 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choferes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chofer',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='chofer',
            name='telefono',
            field=models.CharField(default=None, max_length=12, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener el formato +569XXXXXXXX', regex='^\\+569\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='rut',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe tener entre 7 y 8 dígitos', regex='^\\d{7,8}$')]),
        ),
    ]
