# Generated by Django 5.1.3 on 2024-11-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choferes', '0002_chofer_email_chofer_telefono_alter_chofer_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
