# Generated by Django 5.1.3 on 2024-11-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choferes', '0003_alter_chofer_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='telefono',
            field=models.CharField(max_length=9),
        ),
    ]
