# Generated by Django 5.1.3 on 2024-11-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0002_add_comunas_linares'),
        ('furgones', '0002_alter_furgon_establecimientos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furgon',
            name='establecimientos',
            field=models.ManyToManyField(blank=True, to='establecimientos.establecimiento'),
        ),
    ]
